export const ACTION_TYPE = {
    COMING_CHANGED: "COMING_CHANGED",
    WISHES_CHANGED: "WISHES_CHANGED",
    FOOD_INFO_CHANGED: "FOOD_INFO_CHANGED",
    SONG_WISH_ADDED: "SONG_WISH_ADDED",
    SONG_WISH_REMOVED: "SONG_WISH_REMOVED"
}